# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: candig/metadata/schemas/metadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from candig.metadata.schemas import common_pb2 as candig_dot_metadata_dot_schemas_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='candig/metadata/schemas/metadata.proto',
  package='candig.metadata.schemas',
  syntax='proto3',
  serialized_pb=_b('\n&candig/metadata/schemas/metadata.proto\x12\x17\x63\x61ndig.metadata.schemas\x1a$candig/metadata/schemas/common.proto\"q\n\x07\x44\x61taset\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x37\n\nattributes\x18\x05 \x01(\x0b\x32#.candig.metadata.schemas.Attributesb\x06proto3')
  ,
  dependencies=[candig_dot_metadata_dot_schemas_dot_common__pb2.DESCRIPTOR,])




_DATASET = _descriptor.Descriptor(
  name='Dataset',
  full_name='candig.metadata.schemas.Dataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='candig.metadata.schemas.Dataset.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='candig.metadata.schemas.Dataset.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='candig.metadata.schemas.Dataset.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='candig.metadata.schemas.Dataset.attributes', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=218,
)

_DATASET.fields_by_name['attributes'].message_type = candig_dot_metadata_dot_schemas_dot_common__pb2._ATTRIBUTES
DESCRIPTOR.message_types_by_name['Dataset'] = _DATASET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), dict(
  DESCRIPTOR = _DATASET,
  __module__ = 'candig.metadata.schemas.metadata_pb2'
  # @@protoc_insertion_point(class_scope:candig.metadata.schemas.Dataset)
  ))
_sym_db.RegisterMessage(Dataset)


# @@protoc_insertion_point(module_scope)
